- name: NGINX | Handler | restart service
  service:
    name: nginx
    state: restarted
  listen: restart_nginx

- name: NGINX | Handler | restart tdagent
  service:
    name: td-agent
    state: restarted
  listen: restart_fluentd